[package]
name = "kbs-test"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.9.0", features = ["cookies"] }
anyhow = "1.0.93"
base64 = "0.22.1"
kbs-types = "0.8.0"
lazy_static = "1.5.0"
openssl = "0.10.68"
serde_json = "1.0.133"
uuid = { version = "1.11.0", features = ["v4"] }
